### ISSUE TITLE
追加したテキストを個別にクリップボードにコピーできるようにする

### ISSUE THREAD

**Issue by jiro4989** [jiro4989/sayhissatsuwaza#20]

**Comment by H-ebara** [comment]
`def main():
    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.wait_for_object(2)

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.1, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.enable_trque( True )`

**Comment by H-ebara** [comment]
`def main():
    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.wait_for_object(2)

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.1, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.enable_trque( True )`

**Comment by H-ebara** [comment]
`def main():
    #初期位置へ
    arms.set_init_pose()
    #物体認識する
    camera.wait_for_object(2)

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.1, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.enable_trque( True )`

**Comment by H-ebara** [comment]
`
def main():
    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.wait_for_object(2)

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.1, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.enable_trque( True )`

**Comment by H-ebara** [comment]
`    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.wait_for_object(2, 10)

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.1, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #Homeの位置位置に戻る
    arms.enable_trque( True )
    arms.arm.set_named_target("home")
    arms.arm.go() `

**Comment by H-ebara** [comment]
`  #物体認識する
    camera.wait_for_object(2, 10)

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.1, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #Homeの位置位置に戻る
    arms.enable_trque( True )
    arms.arm.set_named_target("home")
    arms.arm.go() `

**Comment by H-ebara** [comment]
`    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.wait_for_object(2, 10)

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.1, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #Homeの位置位置に戻る
    arms.enable_trque( True )
    arms.arm.set_named_target("home")
    arms.arm.go() `

**Comment by H-ebara** [comment]
`  

  #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.wait_for_object(2, 10)

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.1, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #Homeの位置位置に戻る
    arms.enable_trque( True )
    arms.arm.set_named_target("home")
    arms.arm.go() `

**Comment by H-ebara** [comment]
`def main():
    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.recognize_object()

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.2, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.set_init_pose()`

**Comment by H-ebara** [comment]
'''
def main():
    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.recognize_object()

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.2, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.set_init_pose()
'''

**Comment by H-ebara** [comment]
'''def main():
    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.recognize_object()

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.2, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.set_init_pose()'''

**Comment by H-ebara** [comment]
'''
    #物体認識する
    camera.recognize_object()

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.2, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.set_init_pose()
'''

**Comment by H-ebara** [comment]
'''def main():
    #初期位置へ
    arms.set_init_pose()
    #物体認識する
    camera.recognize_object()

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.2, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.set_init_pose()
'''

**Comment by H-ebara** [comment]
'''

def main():
    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.recognize_object()

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.2, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.set_init_pose()
'''

**Comment by H-ebara** [comment]
'''
   def main()
    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.recognize_object()

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
    #変換後の座標へ移動する
    arms.open_gripper()
    arms.set_pose( p[0], p[1], p[2]+0.2, PI/2, 0, PI/2 )
    arms.open_gripper(False)

    #初期位置に戻る
    arms.set_init_pose()
'''

**Comment by H-ebara** [comment]
'''
def main():
    #初期位置へ
    arms.set_init_pose()

    #物体認識する
    camera.recognize_object()

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
    
'''

**Comment by H-ebara** [comment]
'''
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )
'''

**Comment by H-ebara** [comment]
`p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )`

**Comment by H-ebara** [comment]
あおいいい

'''
    #物体認識する
    camera.wait_for_object(0, 10)

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )

'''

**Comment by H-ebara** [comment]
[https://github.com/naka-lab/ros_actions/blob/master/scripts/move1.py](url)

**Comment by H-ebara** [comment]
座標変換の箇所
`p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )`

**Comment by H-ebara** [comment]
座標変換の箇所

`   camera.recognize_object()

    # 座標変換
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )`

**Comment by H-ebara** [comment]
座標変換の箇所

`   camera.recognize_object()

    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" `)``

**Comment by H-ebara** [comment]
座標変換箇所

`   camera.recognize_object()
    p = utils.transform( camera.target[0], camera.target[1], camera.target[2], "base_link", "camera_depth_optical_frame" )`
